[GLOBAL]
pants_version = "2.4.0.dev0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.flake8",
]
pants_ignore.add = ["!include/"]  # So we don't ignore `mypyc/external/googletest/include/`.

# TODO: This is a bandaid for https://github.com/pantsbuild/pants/issues/7022.
pantsd_invalidation_globs = [
    "*-requirements.txt"
]

[python-infer]
inits = true

[pytest]
config = "pytest.ini"

[flake8]
config = "setup.cfg"
