python_library()

python_tests(
    name="tests",
    dependencies=[
        "test-data",
        "mypy/__main__.py",
        "mypy/dmypy/__main__.py",
        "mypy/test/data.py",
        "mypyc/external/googletest",
    ],
)
